### ISSUE TITLE
Cant run any reproductions when using 8xH100 SXM5

### ISSUE THREAD

**Issue by bluecoconut** [KellerJordan/modded-nanogpt#24]
I've now tried this on different vendors and keep getting errors.

Most recent version is:
I try and run on lambdalabs 8xH100 SXM5, and it fails: https://github.com/KellerJordan/modded-nanogpt/issues/15

so I tried the fix there: `pip install --upgrade nvidia-nccl-cu1`

but im now getting other errors. I've tried with both the most recent record (`111024_UNetDoubleLR` as well as the `train_gpt2.py` thats checked into master).

```
ubuntu@192-222-52-59:~$ nvidia-smi
Mon Nov 11 20:00:18 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.12              Driver Version: 550.90.12      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:61:00.0 Off |                    0 |
| N/A   25C    P0             69W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          On  |   00000000:62:00.0 Off |                    0 |
| N/A   27C    P0             69W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA H100 80GB HBM3          On  |   00000000:63:00.0 Off |                    0 |
| N/A   27C    P0             70W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA H100 80GB HBM3          On  |   00000000:64:00.0 Off |                    0 |
| N/A   26C    P0             72W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA H100 80GB HBM3          On  |   00000000:6A:00.0 Off |                    0 |
| N/A   26C    P0             68W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA H100 80GB HBM3          On  |   00000000:6B:00.0 Off |                    0 |
| N/A   28C    P0             75W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA H100 80GB HBM3          On  |   00000000:6C:00.0 Off |                    0 |
| N/A   27C    P0             68W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA H100 80GB HBM3          On  |   00000000:6D:00.0 Off |                    0 |
| N/A   24C    P0             68W /  700W |       1MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
ppubuntu@192-222-52-59:~$ python -c "import torch; print(torch.__version__)"
2.5.1+cu124
ubuntu@192-222-52-59:~$ 
```

If I run before the nccl install, I get just segfault crashes on the `DDP(model)` line

If I run after the nccl command I get errors like this one (for the most recent `UNetDoubleLr`)
```
[rank4]: The above exception was the direct cause of the following exception:

[rank4]: Traceback (most recent call last):
[rank4]:   File "/home/ubuntu/modded-nanogpt/train_gpt2.py", line 534, in <module>
[rank4]:     loss = model(x, y)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1643, in forward
[rank4]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1459, in _run_ddp_forward
[rank4]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
[rank4]:     return fn(*args, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1263, in __call__
[rank4]:     return hijacked_callback(
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1064, in __call__
[rank4]:     result = self._inner_convert(
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 526, in __call__
[rank4]:     return _compile(
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 924, in _compile
[rank4]:     guarded_code = compile_inner(code, one_graph, hooks, transform)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 666, in compile_inner
[rank4]:     return _compile_inner(code, one_graph, hooks, transform)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
[rank4]:     return function(*args, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 699, in _compile_inner
[rank4]:     out_code = transform_code_object(code, transform)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
[rank4]:     transformations(instructions, code_options)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 219, in _fn
[rank4]:     return fn(*args, **kwargs)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 634, in transform
[rank4]:     tracer.run()
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2796, in run
[rank4]:     super().run()
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
[rank4]:     while self.step():
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
[rank4]:     self.dispatch_table[inst.opcode](self, inst)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2987, in RETURN_VALUE
[rank4]:     self._return(inst)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2972, in _return
[rank4]:     self.output.compile_subgraph(
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1117, in compile_subgraph
[rank4]:     self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1369, in compile_and_call_fx_graph
[rank4]:     compiled_fn = self.call_user_compiler(gm)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1416, in call_user_compiler
[rank4]:     return self._call_user_compiler(gm)
[rank4]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1465, in _call_user_compiler
[rank4]:     raise BackendCompilerFailed(self.compiler_fn, e) from e
[rank4]: torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
[rank4]: ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

[rank4]: While executing %submod_0 : [num_users=3] = call_module[target=submod_0](args = (%l_idx_, %l_self_modules_transformer_modules_wte_parameters_weight_, %l_self_modules_transformer_modules_h_modules_0_parameters_lambdas_), kwargs = {})
[rank4]: Original traceback:
[rank4]: None

[rank4]: Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


[rank4]: You can suppress this exception and fall back to eager by setting:
[rank4]:     import torch._dynamo
[rank4]:     torch._dynamo.config.suppress_errors = True
```

If i turn on 
```
import torch._dynamo
torch._dynamo.config.suppress_errors = True
```
in the code, i get OOM errors

==

Running just the main `train_gpt2.py` script, I get 
```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1446, in _call_user_compiler
[rank1]:     compiled_fn = compiler_fn(gm, self.example_inputs())
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/backends/distributed.py", line 546, in compile_fn
[rank1]:     submod_compiler.run(*example_inputs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/fx/interpreter.py", line 146, in run
[rank1]:     self.env[node] = self.run_node(node)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/backends/distributed.py", line 266, in run_node
[rank1]:     compiled_submod_real = self.compile_submod(real_mod, new_args, kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/backends/distributed.py", line 181, in compile_submod
[rank1]:     self.compiler(input_mod, args),
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
[rank1]:     compiled_gm = compiler_fn(gm, example_inputs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/__init__.py", line 2234, in __call__
[rank1]:     return compile_fx(model_, inputs_, config_patches=self.config)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1521, in compile_fx
[rank1]:     return aot_autograd(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 72, in __call__
[rank1]:     cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1071, in aot_module_simplified
[rank1]:     compiled_fn = dispatch_and_compile()
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1056, in dispatch_and_compile
[rank1]:     compiled_fn, _ = create_aot_dispatcher_function(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 522, in create_aot_dispatcher_function
[rank1]:     return _create_aot_dispatcher_function(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 759, in _create_aot_dispatcher_function
[rank1]:     compiled_fn, fw_metadata = compiler_fn(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 382, in aot_dispatch_autograd
[rank1]:     fw_module, bw_module = aot_config.partition_fn(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1449, in partition_fn
[rank1]:     return min_cut_rematerialization_partition(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/partitioners.py", line 1850, in min_cut_rematerialization_partition
[rank1]:     saved_values = choose_saved_values_set(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/partitioners.py", line 1571, in choose_saved_values_set
[rank1]:     runtime_optimized_saved_values, _ = solve_min_cut(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_functorch/partitioners.py", line 849, in solve_min_cut
[rank1]:     import networkx as nx
[rank1]:   File "/usr/lib/python3/dist-packages/networkx/__init__.py", line 112, in <module>
[rank1]:     import networkx.generators
[rank1]:   File "/usr/lib/python3/dist-packages/networkx/generators/__init__.py", line 8, in <module>
[rank1]:     from networkx.generators.community import *
[rank1]:   File "/usr/lib/python3/dist-packages/networkx/generators/community.py", line 20, in <module>
[rank1]:     from scipy.special import zeta as _zeta
[rank1]:   File "/usr/lib/python3/dist-packages/scipy/special/__init__.py", line 649, in <module>
[rank1]:     from . import _ufuncs
[rank1]:   File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
[rank1]: ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

[rank1]: While executing %submod_0 : [num_users=3] = call_module[target=submod_0](args = (%l_idx_, %l_self_modules_transformer_modules_wte_parameters_weight_, %l_self_modules_transformer_modules_h_modules_0_parameters_lambdas_), kwargs = {})
[rank1]: Original traceback:
[rank1]: None

[rank1]: The above exception was the direct cause of the following exception:

[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/ubuntu/modded-nanogpt/train_gpt2.py", line 519, in <module>
[rank1]:     loss = model(x, y)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1643, in forward
[rank1]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1459, in _run_ddp_forward
[rank1]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
[rank1]:     return fn(*args, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1263, in __call__
[rank1]:     return hijacked_callback(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1064, in __call__
[rank1]:     result = self._inner_convert(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 526, in __call__
[rank1]:     return _compile(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 924, in _compile
[rank1]:     guarded_code = compile_inner(code, one_graph, hooks, transform)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 666, in compile_inner
[rank1]:     return _compile_inner(code, one_graph, hooks, transform)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
[rank1]:     return function(*args, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 699, in _compile_inner
[rank1]:     out_code = transform_code_object(code, transform)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
[rank1]:     transformations(instructions, code_options)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 219, in _fn
[rank1]:     return fn(*args, **kwargs)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 634, in transform
[rank1]:     tracer.run()
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2796, in run
[rank1]:     super().run()
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
[rank1]:     while self.step():
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
[rank1]:     self.dispatch_table[inst.opcode](self, inst)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2987, in RETURN_VALUE
[rank1]:     self._return(inst)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2972, in _return
[rank1]:     self.output.compile_subgraph(
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1117, in compile_subgraph
[rank1]:     self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1369, in compile_and_call_fx_graph
[rank1]:     compiled_fn = self.call_user_compiler(gm)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1416, in call_user_compiler
[rank1]:     return self._call_user_compiler(gm)
[rank1]:   File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1465, in _call_user_compiler
[rank1]:     raise BackendCompilerFailed(self.compiler_fn, e) from e
[rank1]: torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
[rank1]: ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

[rank1]: While executing %submod_0 : [num_users=3] = call_module[target=submod_0](args = (%l_idx_, %l_self_modules_transformer_modules_wte_parameters_weight_, %l_self_modules_transformer_modules_h_modules_0_parameters_lambdas_), kwargs = {})
[rank1]: Original traceback:
[rank1]: None

[rank1]: Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

Here's some more env info:
```
ubuntu@192-222-52-59:~/modded-nanogpt$ pip freeze | grep nvidia
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-ml-py==12.555.43
nvidia-nccl-cu12==2.23.4
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
```

```
ubuntu@192-222-52-59:~/modded-nanogpt$ pip freeze | grep torch
torch==2.5.1
torchvision==0.18.1
```

**Comment by bluecoconut** [comment]
aha! Finally got it running. 

I wasn't sure if it was a driver issue or a cuda issue, and it seems like pytorch compiled for 12.4 but running on cuda 12.5 or 12.6 is required. 

I'll add a docker version as a PR tonight or tomorrow -- since that's how I got it to run and likely could solve a lot of headache in the future for reproductions. 
Started with: `nvidia/cuda:12.6.2-devel-ubuntu22.04`, and even though the driver version is still: `Driver Version: 550.90.12` (different from the logs of the benchmark you have posted)

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.12              Driver Version: 550.90.12      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
```

with this base image, i installed python 3.12.7, then ran and it seems to be running along, and im getting very close (~2 ms difference) in time per step - (145ms vs. 143 ish)

```
step:1783/3242 train_loss:3.3365 train_time:257684ms step_avg:145.34ms
step:1784/3242 train_loss:3.4149 train_time:257826ms step_avg:145.34ms
step:1785/3242 train_loss:3.5628 train_time:257971ms step_avg:145.34ms
```

**Comment by KellerJordan** [comment]
interesting, glad it's working now. thanks for posting your experience
