### ISSUE TITLE
Consistent SIGSEGV on 8xH100

### ISSUE THREAD

**Issue by scottjmaddox** [KellerJordan/modded-nanogpt#50]
Anyone else getting consistent SIGSEGV's on 8xH100? In particular on Lambda Cloud's gpu_8x_h100_sxm5. I've reproduced this on 2 different nodes (in different regions). It also occurs on older versions of the repo. I'm guessing one of the dependencies changed. Perhaps time to add a lock file to the repo, e.g. using [uv](https://github.com/astral-sh/uv)?

Full repro after bootup and login:

```sh
git clone https://github.com/KellerJordan/modded-nanogpt
cd modded-nanogpt
pip install -r requirements.txt
pip install --pre torch==2.6.0.dev20241203+cu124 --index-url https://download.pytorch.org/whl/nightly/cu124 --upgrade # install torch 2.6.0
python data/cached_fineweb10B.py 10 # downloads only the first 1.0B training tokens to save time
./run.sh
```

Result:
```
W1210 04:04:55.628000 6579 torch/distributed/run.py:792] 
W1210 04:04:55.628000 6579 torch/distributed/run.py:792] *****************************************
W1210 04:04:55.628000 6579 torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1210 04:04:55.628000 6579 torch/distributed/run.py:792] *****************************************
using device: cuda:0
Running python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Running pytorch 2.6.0.dev20241203+cu124 compiled for CUDA 12.4
nvidia-smi:
using device: cuda:2
using device: cuda:6
using device: cuda:3
using device: cuda:1
using device: cuda:5
using device: cuda:4
Training DataLoader: total number of tokens: 1000000000 across 10 files
Validation DataLoader: total number of tokens: 100000000 across 1 files
using device: cuda:7
W1210 04:05:23.394000 6579 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 7229 closing signal SIGTERM
W1210 04:05:23.394000 6579 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 7230 closing signal SIGTERM
W1210 04:05:23.394000 6579 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 7231 closing signal SIGTERM
W1210 04:05:23.395000 6579 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 7233 closing signal SIGTERM
W1210 04:05:23.395000 6579 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 7234 closing signal SIGTERM
W1210 04:05:23.395000 6579 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 7235 closing signal SIGTERM
W1210 04:05:23.395000 6579 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 7236 closing signal SIGTERM
E1210 04:05:24.137000 6579 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -11) local_rank: 3 (pid: 7232) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 918, in main
    run(args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
train_gpt2.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-10_04:05:23
  host      : 192-222-53-224
  rank      : 3 (local_rank: 3)
  exitcode  : -11 (pid: 7232)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 7232
======================================================
```

**Comment by leloykun** [comment]
I haven't been able to make this work on Lambda Cloud myself

I'm guessing it has to do with their memory sharing settings with Docker/Kubernetes

**Comment by bkoszarsky** [comment]
Running via Docker will work on Lambda Cloud
```
sudo docker build -t modded-nanogpt .
sudo docker run -it --rm --gpus all -v $(pwd):/modded-nanogpt modded-nanogpt python data/cached_fineweb10B.py 10
sudo docker run -it --rm --gpus all -v $(pwd):/modded-nanogpt modded-nanogpt sh run.sh
```

**Comment by scottjmaddox** [comment]
Hmm, that's a good point, this is the first time I've successfully rented an 8xH100 from LambdaLabs. The previous time I ran 8xH100 was on RunPod. Their 1xH100's work fine, though. While, oddly, running a single-node job on the 8xH100 had the same SIGSEGV issue...

**Comment by scottjmaddox** [comment]
> Running via Docker will work on Lambda Cloud

Interesting. So it must be something installed on the node by default, e.g. python, that's the problem.
